export const ADD_USER = 'ADD_USER';
export const SET_USER_CURRENCY = 'SET_USER_CURRENCY';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_CONVERT = 'GET_CONVERT';
export const SET_CONVERT = 'SET_CONVERT';

export const GET_RATES = 'GET_RATES';
export const SET_RATES = 'SET_RATES';

export const GET_CURRENCIES_LIST = 'GET_CURRENCIES_LIST';
export const SET_CURRENCIES_LIST = 'SET_CURRENCIES_LIST';